name: Build and deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.15.0
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.13.2
      - name: Install Depot
        run: curl https://raw.githubusercontent.com/cognitive-engineering-lab/depot/main/scripts/install.sh | sh
      - name: Publish
        run: ./publish.sh
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/client
